//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class aaFieldTypeExample
    {
        public int aaFieldTypeExampleID { get; set; }
        public Nullable<long> a_bigint { get; set; }
        public byte[] a_binary_50 { get; set; }
        public Nullable<bool> a_bit { get; set; }
        public string a_char_10 { get; set; }
        public Nullable<System.DateTime> a_date { get; set; }
        public Nullable<System.DateTime> a_datetime { get; set; }
        public Nullable<System.DateTime> a_datetime2_7 { get; set; }
        public Nullable<System.DateTimeOffset> a_datetimeoffsert_7 { get; set; }
        public Nullable<decimal> a_decimal_18_0 { get; set; }
        public Nullable<double> a_float { get; set; }
        public System.Data.Entity.Spatial.DbGeography a_geography { get; set; }
        public System.Data.Entity.Spatial.DbGeometry a_geometry { get; set; }
        public byte[] a_image { get; set; }
        public Nullable<int> a_int { get; set; }
        public Nullable<decimal> a_money { get; set; }
        public string a_nchar_10 { get; set; }
        public string a_ntext { get; set; }
        public Nullable<decimal> a_numeric_18_0 { get; set; }
        public string a_nvarchar_50 { get; set; }
        public string a_nvarchar_MAX { get; set; }
        public Nullable<float> a_real { get; set; }
        public Nullable<System.DateTime> a_smalldatetime { get; set; }
        public Nullable<short> a_smallint { get; set; }
        public Nullable<decimal> a_smallmoney { get; set; }
        public string a_text { get; set; }
        public Nullable<System.TimeSpan> a_time_7 { get; set; }
        public byte[] a_timestamp { get; set; }
        public Nullable<byte> a_tinyint { get; set; }
        public Nullable<System.Guid> a_uniqueidentifier { get; set; }
        public byte[] a_varbinary_50 { get; set; }
        public byte[] a_varbinary_MAX { get; set; }
        public string a_varchar_50 { get; set; }
        public string a_varchar_MAX { get; set; }
        public string a_xml { get; set; }
    }
}
