//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppErrLog
    {
        public int AppErrLogID { get; set; }
        public string AppErrLogUniqueTag { get; set; }
        public int AppErrLogLineNumber { get; set; }
        public string AppErrLogSource { get; set; }
        public string AppErrLogMessage { get; set; }
        public System.DateTime AppErrLogDateTime { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
