//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLog
    {
        public int AppLogID { get; set; }
        public string AppLogTable { get; set; }
        public string AppLogActivity { get; set; }
        public string AppLogMoreInfo { get; set; }
        public System.DateTime AppLogDateTime { get; set; }
        public int EnteredByID { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
