//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppTask
    {
        public int AppTaskID { get; set; }
        public Nullable<int> AppUserInfoID { get; set; }
        public Nullable<int> CSSPItemID { get; set; }
        public string AppTaskBusyInfo { get; set; }
        public string AppTaskStatus { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<double> AppTaskEstimatedLengthInMinutes { get; set; }
        public Nullable<double> AppTaskRemainingTimeInMinutes { get; set; }
        public string AppTaskError { get; set; }
        public string AppTaskCultureName { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual AppUserInfo AppUserInfo { get; set; }
        public virtual CSSPItem CSSPItem { get; set; }
    }
}
