//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADSample
    {
        public int ASGADSampleID { get; set; }
        public string p { get; set; }
        public string PROV { get; set; }
        public string AREA { get; set; }
        public string SECTOR { get; set; }
        public string SUBSECTOR { get; set; }
        public Nullable<System.DateTime> SAMP_DATE { get; set; }
        public Nullable<int> RUN_NUMBER { get; set; }
        public string STAT_NBR { get; set; }
        public string SAMP_TIME { get; set; }
        public Nullable<double> FEC_COL { get; set; }
        public Nullable<double> SALINITY { get; set; }
        public Nullable<double> WATERTEMP { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
    }
}
