//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADSubsect
    {
        public int ASGADSubsectID { get; set; }
        public string p { get; set; }
        public string PROV { get; set; }
        public string AREA { get; set; }
        public string SECTOR { get; set; }
        public string SUBSECTOR { get; set; }
        public string DFO_CODE { get; set; }
        public string NAME { get; set; }
        public string DESCRIPT { get; set; }
        public string MAP { get; set; }
        public string PRECIPID { get; set; }
        public string PRECIPID2 { get; set; }
        public string PRECIPID3 { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
    }
}
