//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADRun
    {
        public int ASGADRunID { get; set; }
        public string p { get; set; }
        public string PROV { get; set; }
        public string AREA { get; set; }
        public string SECTOR { get; set; }
        public string SUBSECTOR { get; set; }
        public Nullable<System.DateTime> SAMP_DATE { get; set; }
        public Nullable<int> RUN_NUMBER { get; set; }
        public string START_TIME { get; set; }
        public string FIN_TIME { get; set; }
        public string TIDE_CODE { get; set; }
        public string TIDEF_CODE { get; set; }
        public string AUTOCALC { get; set; }
        public Nullable<double> PPT24 { get; set; }
        public Nullable<double> PPT48 { get; set; }
        public Nullable<double> PPT72 { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
    }
}
