//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADPrecStn
    {
        public int ASGADPrecStnID { get; set; }
        public string p { get; set; }
        public string NAME { get; set; }
        public string PROV { get; set; }
        public string ID { get; set; }
        public string LAT { get; set; }
        public string LONG { get; set; }
        public Nullable<double> LAT_DEG { get; set; }
        public Nullable<double> LONG_DEG { get; set; }
        public Nullable<double> ELEV { get; set; }
    }
}
