//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADTide
    {
        public int ASGADSTideID { get; set; }
        public string p { get; set; }
        public string TIDE_CODE { get; set; }
        public string TIDE_NAME { get; set; }
    }
}
