//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADPrecData
    {
        public int ASGADPrecDataID { get; set; }
        public string p { get; set; }
        public string PROV { get; set; }
        public string PRECIPID { get; set; }
        public Nullable<System.DateTime> SAMP_DATE { get; set; }
        public Nullable<double> PRECIP { get; set; }
    }
}
