//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADMPNTable
    {
        public int ASGADMPNTableID { get; set; }
        public string p { get; set; }
        public string TUBE5_10 { get; set; }
        public string TUBE5_1 { get; set; }
        public string TUBE5_01 { get; set; }
        public string MPN { get; set; }
    }
}
