//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADStation
    {
        public int ASGADStationID { get; set; }
        public string p { get; set; }
        public string PROV { get; set; }
        public string AREA { get; set; }
        public string SECTOR { get; set; }
        public string SUBSECTOR { get; set; }
        public string STAT_NBR { get; set; }
        public string STAT_NAME { get; set; }
        public string STAT_TYPE { get; set; }
        public string SORT_ORDER { get; set; }
        public string ZONE { get; set; }
        public string EASTING { get; set; }
        public string NORTHING { get; set; }
        public Nullable<double> LAT { get; set; }
        public Nullable<double> LONG { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
    }
}
