//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADSampCode
    {
        public int ASGADSampCodeID { get; set; }
        public string p { get; set; }
        public string SAMPCODE { get; set; }
        public string OTH_CODE { get; set; }
        public string SAMPNAME { get; set; }
        public string UNITS { get; set; }
        public string LOW_LIMIT { get; set; }
        public string HIGH_LIMIT { get; set; }
    }
}
