//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCLandSampleStation
    {
        public int BCLandSampleStationID { get; set; }
        public string SS_STATION { get; set; }
        public string SS_DESCRIP { get; set; }
        public string SS_SHELLFI { get; set; }
        public string SS_STATUS { get; set; }
        public Nullable<double> LAT { get; set; }
        public Nullable<double> LON { get; set; }
        public string Pub { get; set; }
    }
}
