//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCMarineSample
    {
        public int BCMarineSampleID { get; set; }
        public Nullable<int> SR_SURVEY { get; set; }
        public string SR_STATION_CODE { get; set; }
        public string SR_ANALYSIS_TYPE { get; set; }
        public Nullable<System.DateTime> SR_READING_DATE { get; set; }
        public string SR_READING_TIME { get; set; }
        public string SR_SAMPLE_TYPE { get; set; }
        public Nullable<double> SR_SAMPLE_DEPTH { get; set; }
        public string SR_FECAL_COLIFORM_IND { get; set; }
        public Nullable<int> SR_FECAL_COLIFORM { get; set; }
        public string SR_ENTEROCOCCI_IND { get; set; }
        public Nullable<int> SR_ENTEROCOCCI { get; set; }
        public Nullable<double> SR_SALINITY { get; set; }
        public Nullable<double> SR_TEMPERATURE { get; set; }
        public Nullable<double> SR_TURBIDITY { get; set; }
        public string SR_TIDE_CODE { get; set; }
        public string SR_SPECIES { get; set; }
        public Nullable<int> SR_SAMPLE_AGENCY { get; set; }
        public string SR_OBS { get; set; }
    }
}
