//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCPolSource
    {
        public int BCPolSourceID { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public string Verified { get; set; }
        public string Source_nme { get; set; }
        public string Label { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string LCode { get; set; }
        public string ICode { get; set; }
        public string Key_ { get; set; }
        public Nullable<double> X_calc { get; set; }
        public Nullable<double> Y_calc { get; set; }
        public string DATALINK { get; set; }
        public Nullable<System.DateTime> yyyymmdd { get; set; }
        public string Remarks { get; set; }
        public string LatDegMin { get; set; }
        public string LonDegMin { get; set; }
    }
}
