//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCSurvey
    {
        public int BCSurveyID { get; set; }
        public Nullable<int> S_ID_NUMBER { get; set; }
        public string S_SHELLFISH_SECTOR { get; set; }
        public string S_DESCRIPTION { get; set; }
        public string S_SURVEY_TYPE { get; set; }
        public Nullable<System.DateTime> S_START_DATE { get; set; }
        public Nullable<System.DateTime> S_END_DATE { get; set; }
        public string S_COMMENT { get; set; }
    }
}
