//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxModel
    {
        public BoxModel()
        {
            this.BoxModelResults = new HashSet<BoxModelResult>();
        }
    
        public int BoxModelID { get; set; }
        public int CSSPItemID { get; set; }
        public string ScenarioName { get; set; }
        public Nullable<double> Flow { get; set; }
        public Nullable<double> Depth { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> Dilution { get; set; }
        public Nullable<double> DecayRate { get; set; }
        public Nullable<double> FCUntreated { get; set; }
        public Nullable<double> FCPreDisinfection { get; set; }
        public Nullable<double> Concentration { get; set; }
        public Nullable<double> T90 { get; set; }
        public Nullable<double> FlowDuration { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<BoxModelResult> BoxModelResults { get; set; }
        public virtual CSSPItem CSSPItem { get; set; }
    }
}
