//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxModelResult
    {
        public int BoxModelID { get; set; }
        public int ResultType { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> Surface { get; set; }
        public Nullable<double> Radius { get; set; }
        public Nullable<double> LeftSideDiameterLineAngle { get; set; }
        public Nullable<double> CircleCenterLatitude { get; set; }
        public Nullable<double> CircleCenterLongitude { get; set; }
        public Nullable<bool> FixLength { get; set; }
        public Nullable<bool> FixWidth { get; set; }
        public Nullable<double> RectLength { get; set; }
        public Nullable<double> RectWidth { get; set; }
        public Nullable<double> LeftSideLineAngle { get; set; }
        public Nullable<double> LeftSideLineStartLatitude { get; set; }
        public Nullable<double> LeftSideLineStartLongitude { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual BoxModel BoxModel { get; set; }
    }
}
