//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSSPItemType
    {
        public CSSPItemType()
        {
            this.CSSPItems = new HashSet<CSSPItem>();
            this.CSSPItemTypeLanguages = new HashSet<CSSPItemTypeLanguage>();
            this.CSSPItemTypePaths = new HashSet<CSSPItemTypePath>();
            this.CSSPItemTypePaths1 = new HashSet<CSSPItemTypePath>();
            this.CSSPItemTypesUserAuthorizations = new HashSet<CSSPItemTypesUserAuthorization>();
        }
    
        public int CSSPItemTypeID { get; set; }
        public string CSSPItemTypeTextENLowered { get; set; }
        public bool CanContainMultiple { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int ModifiedByID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CSSPItem> CSSPItems { get; set; }
        public virtual ICollection<CSSPItemTypeLanguage> CSSPItemTypeLanguages { get; set; }
        public virtual ICollection<CSSPItemTypePath> CSSPItemTypePaths { get; set; }
        public virtual ICollection<CSSPItemTypePath> CSSPItemTypePaths1 { get; set; }
        public virtual ICollection<CSSPItemTypesUserAuthorization> CSSPItemTypesUserAuthorizations { get; set; }
    }
}
