//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSSPFile
    {
        public CSSPFile()
        {
            this.CSSPFileContents = new HashSet<CSSPFileContent>();
            this.CSSPFileInfos = new HashSet<CSSPFileInfo>();
            this.CSSPItemFiles = new HashSet<CSSPItemFile>();
            this.MikeScenarioFiles = new HashSet<MikeScenarioFile>();
        }
    
        public int CSSPFileID { get; set; }
        public string FileName { get; set; }
        public string Purpose { get; set; }
        public string FileOriginalPath { get; set; }
        public string FileDescription { get; set; }
        public string FileType { get; set; }
        public Nullable<long> FileSize { get; set; }
        public Nullable<System.DateTime> FileCreatedDate { get; set; }
        public string ServerFileName { get; set; }
        public string ServerFilePath { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<CSSPFileContent> CSSPFileContents { get; set; }
        public virtual ICollection<CSSPFileInfo> CSSPFileInfos { get; set; }
        public virtual ICollection<CSSPItemFile> CSSPItemFiles { get; set; }
        public virtual ICollection<MikeScenarioFile> MikeScenarioFiles { get; set; }
    }
}
