//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSSPInfrastructure
    {
        public int CSSPInfrastructureID { get; set; }
        public int CSSPItemID { get; set; }
        public string Category { get; set; }
        public Nullable<int> PrismID { get; set; }
        public Nullable<int> TPID { get; set; }
        public Nullable<int> LSID { get; set; }
        public string InfrastructureType { get; set; }
        public string YearOfAssessment { get; set; }
        public Nullable<int> SiteID { get; set; }
        public string Locator { get; set; }
        public Nullable<System.DateTime> DateSite { get; set; }
        public Nullable<int> Site { get; set; }
        public string Datum { get; set; }
        public Nullable<int> Zone { get; set; }
        public Nullable<double> Easting { get; set; }
        public Nullable<double> Northing { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> TimeZone { get; set; }
        public Nullable<double> DesignFlow { get; set; }
        public Nullable<double> AverageFlow { get; set; }
        public Nullable<double> PeakFlow { get; set; }
        public Nullable<double> EstimatedFlow { get; set; }
        public Nullable<int> PopDesign { get; set; }
        public Nullable<int> PopServed { get; set; }
        public Nullable<double> PopServedPerc { get; set; }
        public Nullable<int> PopNotServed { get; set; }
        public Nullable<double> PopNotServedPerc { get; set; }
        public Nullable<System.DateTime> DateOfConstruction { get; set; }
        public Nullable<System.DateTime> DateOfRecentUpgrade { get; set; }
        public Nullable<int> NumbOfResidentialBuilding { get; set; }
        public Nullable<double> NumbOfResidentialBuildingPerc { get; set; }
        public Nullable<int> NumbOfCommercialBuilding { get; set; }
        public Nullable<double> NumbOfCommercialBuildingPerc { get; set; }
        public string PrimaryTypeOfIndustry { get; set; }
        public string SecondaryTypeOfIndustry { get; set; }
        public string TreatmentType { get; set; }
        public string OperatorName { get; set; }
        public string OperatorTelephone { get; set; }
        public string OperatorEmail { get; set; }
        public Nullable<int> NumbOfVisitToPlantPerWeek { get; set; }
        public string Disinfection { get; set; }
        public Nullable<int> BODRequired { get; set; }
        public Nullable<int> SSRequired { get; set; }
        public Nullable<int> FCRequired { get; set; }
        public Nullable<bool> HasAlarmSystem { get; set; }
        public string AlarmSystemTypeAndComment { get; set; }
        public string CollectionSystemType { get; set; }
        public Nullable<double> CombinedPercent { get; set; }
        public Nullable<int> PercentOfTotalFlow { get; set; }
        public Nullable<int> BypassFrequency { get; set; }
        public string BypassTypeOrCause { get; set; }
        public Nullable<int> BypassAverageTime { get; set; }
        public Nullable<double> BypassNotificationTime { get; set; }
        public string LagoonOrMechanical { get; set; }
        public Nullable<bool> Significant { get; set; }
        public string OutfallDatum { get; set; }
        public Nullable<int> OutfallPrismID { get; set; }
        public Nullable<int> OutfallZone { get; set; }
        public Nullable<double> OutfallEasting { get; set; }
        public Nullable<double> OutfallNorthing { get; set; }
        public Nullable<double> OutfallLatitude { get; set; }
        public Nullable<double> OutfallLongitude { get; set; }
        public Nullable<double> OutfallDepthHigh { get; set; }
        public Nullable<double> OutfallDepthLow { get; set; }
        public Nullable<int> OutfallNumberOfPorts { get; set; }
        public Nullable<double> OutfallPortDiameter { get; set; }
        public Nullable<double> OutfallPortSpacing { get; set; }
        public Nullable<double> OutfallPortElevation { get; set; }
        public Nullable<int> OutfallVerticalAngle { get; set; }
        public Nullable<int> OutfallHorizontalAngle { get; set; }
        public Nullable<double> OutfallDecayRate { get; set; }
        public Nullable<double> OutfallNearFieldVelocity { get; set; }
        public Nullable<double> OutfallFarFieldVelocity { get; set; }
        public Nullable<double> OutfallReceivingWaterSalinity { get; set; }
        public Nullable<double> OutfallReceivingWaterTemperature { get; set; }
        public Nullable<double> OutfallReceivingWaterFC { get; set; }
        public Nullable<double> OutfallDistanceFromShore { get; set; }
        public string ReceivingWaterName { get; set; }
        public string InputDataComments { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual CSSPItem CSSPItem { get; set; }
    }
}
