//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class MikeSourceStartEnd
    {
        public int MikeSourceStartEndID { get; set; }
        public int MikeSourceID { get; set; }
        public Nullable<System.DateTime> StartDateAndTime { get; set; }
        public Nullable<System.DateTime> EndDateAndTime { get; set; }
        public Nullable<double> SourceFlowStart { get; set; }
        public Nullable<double> SourceFlowEnd { get; set; }
        public Nullable<double> SourcePollutionStart { get; set; }
        public Nullable<double> SourcePollutionEnd { get; set; }
        public Nullable<double> SourceTemperatureStart { get; set; }
        public Nullable<double> SourceTemperatureEnd { get; set; }
        public Nullable<double> SourceSalinityStart { get; set; }
        public Nullable<double> SourceSalinityEnd { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual MikeSource MikeSource { get; set; }
    }
}
