//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class MikeBoundaryCondition
    {
        public MikeBoundaryCondition()
        {
            this.MikeBoundaryConditionNodes = new HashSet<MikeBoundaryConditionNode>();
            this.MikeBoundaryConditionWebTideNodes = new HashSet<MikeBoundaryConditionWebTideNode>();
        }
    
        public int MikeBoundaryConditionID { get; set; }
        public int MikeScenarioID { get; set; }
        public string BoundaryConditionCode { get; set; }
        public string BoundaryConditionName { get; set; }
        public double BoundaryConditionLength { get; set; }
        public string BoundaryConditionFormat { get; set; }
        public string BoundaryConditionType { get; set; }
        public string WebTideModel { get; set; }
        public int NumberOfWebTideNodes { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<MikeBoundaryConditionNode> MikeBoundaryConditionNodes { get; set; }
        public virtual MikeScenario MikeScenario { get; set; }
        public virtual ICollection<MikeBoundaryConditionWebTideNode> MikeBoundaryConditionWebTideNodes { get; set; }
    }
}
