//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class MikeSource
    {
        public MikeSource()
        {
            this.MikeSourceStartEnds = new HashSet<MikeSourceStartEnd>();
        }
    
        public int MikeSourceID { get; set; }
        public int MikeScenarioID { get; set; }
        public string SourceName { get; set; }
        public Nullable<bool> Include { get; set; }
        public Nullable<bool> IsContinuous { get; set; }
        public Nullable<double> SourceLat { get; set; }
        public Nullable<double> SourceLong { get; set; }
        public string SourceNumberString { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual MikeScenario MikeScenario { get; set; }
        public virtual ICollection<MikeSourceStartEnd> MikeSourceStartEnds { get; set; }
    }
}
