//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomenclature
    {
        public int ID { get; set; }
        public string Locator { get; set; }
        public string Area { get; set; }
        public string Sector { get; set; }
        public string DFO { get; set; }
        public string Subsector { get; set; }
        public string SubsectorDesc { get; set; }
        public string Map { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
