//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSSPAppDB2Entities : DbContext
    {
        public CSSPAppDB2Entities()
            : base("name=CSSPAppDB2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aaFieldTypeExample> aaFieldTypeExamples { get; set; }
        public virtual DbSet<AppErrLog> AppErrLogs { get; set; }
        public virtual DbSet<AppLanguage> AppLanguages { get; set; }
        public virtual DbSet<AppLog> AppLogs { get; set; }
        public virtual DbSet<AppTask> AppTasks { get; set; }
        public virtual DbSet<AppUserInfo> AppUserInfos { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<BoxModelResult> BoxModelResults { get; set; }
        public virtual DbSet<BoxModel> BoxModels { get; set; }
        public virtual DbSet<CSSPFileContent> CSSPFileContents { get; set; }
        public virtual DbSet<CSSPFileInfo> CSSPFileInfos { get; set; }
        public virtual DbSet<CSSPFile> CSSPFiles { get; set; }
        public virtual DbSet<CSSPInfrastructure> CSSPInfrastructures { get; set; }
        public virtual DbSet<CSSPItemFile> CSSPItemFiles { get; set; }
        public virtual DbSet<CSSPItemLanguage> CSSPItemLanguages { get; set; }
        public virtual DbSet<CSSPItemPath> CSSPItemPaths { get; set; }
        public virtual DbSet<CSSPItem> CSSPItems { get; set; }
        public virtual DbSet<CSSPItemsUserAuthorization> CSSPItemsUserAuthorizations { get; set; }
        public virtual DbSet<CSSPItemTypeLanguage> CSSPItemTypeLanguages { get; set; }
        public virtual DbSet<CSSPItemTypePath> CSSPItemTypePaths { get; set; }
        public virtual DbSet<CSSPItemType> CSSPItemTypes { get; set; }
        public virtual DbSet<CSSPItemTypesUserAuthorization> CSSPItemTypesUserAuthorizations { get; set; }
        public virtual DbSet<MikeBoundaryConditionNode> MikeBoundaryConditionNodes { get; set; }
        public virtual DbSet<MikeBoundaryCondition> MikeBoundaryConditions { get; set; }
        public virtual DbSet<MikeBoundaryConditionWebTideNode> MikeBoundaryConditionWebTideNodes { get; set; }
        public virtual DbSet<MikeParameter> MikeParameters { get; set; }
        public virtual DbSet<MikeScenarioFile> MikeScenarioFiles { get; set; }
        public virtual DbSet<MikeScenario> MikeScenarios { get; set; }
        public virtual DbSet<MikeSource> MikeSources { get; set; }
        public virtual DbSet<MikeSourceStartEnd> MikeSourceStartEnds { get; set; }
        public virtual DbSet<OldCityDone> OldCityDones { get; set; }
        public virtual DbSet<ResetPassword> ResetPasswords { get; set; }
        public virtual DbSet<VPAmbient> VPAmbients { get; set; }
        public virtual DbSet<VPScenario> VPScenarios { get; set; }
        public virtual DbSet<VPSelectedCormixResult> VPSelectedCormixResults { get; set; }
        public virtual DbSet<VPSelectedResult> VPSelectedResults { get; set; }
        public virtual DbSet<VPValuedCormixResult> VPValuedCormixResults { get; set; }
        public virtual DbSet<VPValuedResult> VPValuedResults { get; set; }
        public virtual DbSet<WQMDefPrecipStation> WQMDefPrecipStations { get; set; }
        public virtual DbSet<WQMMPN> WQMMPNs { get; set; }
        public virtual DbSet<WQMPrecipStation> WQMPrecipStations { get; set; }
        public virtual DbSet<WQMPrecipValue> WQMPrecipValues { get; set; }
        public virtual DbSet<WQMRun> WQMRuns { get; set; }
        public virtual DbSet<WQMSampleCode> WQMSampleCodes { get; set; }
        public virtual DbSet<WQMSample> WQMSamples { get; set; }
        public virtual DbSet<WQMStation> WQMStations { get; set; }
        public virtual DbSet<WQMSubsecDefPrecipStation> WQMSubsecDefPrecipStations { get; set; }
        public virtual DbSet<WQMSubsector> WQMSubsectors { get; set; }
        public virtual DbSet<WQMTide> WQMTides { get; set; }
    }
}
