//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCClimateSite
    {
        public int QCClimateSiteID { get; set; }
        public string station_meteo { get; set; }
        public string ClimateSiteName { get; set; }
        public string ClimateID { get; set; }
    }
}
