//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCSecteurMPol
    {
        public int QCSecteurMPolID { get; set; }
        public string Subsector { get; set; }
        public Nullable<int> geo_pollution_id { get; set; }
    }
}
