//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCSubSector
    {
        public int QCSubSectorID { get; set; }
        public string QCSubSectorLetter { get; set; }
        public string QCSubSectorTextEN { get; set; }
        public string QCSubSectorTextFR { get; set; }
    }
}
