//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPAmbient
    {
        public int VPScenarioID { get; set; }
        public int Row { get; set; }
        public double MeasurementDepth { get; set; }
        public double CurrentSpeed { get; set; }
        public double CurrentDirection { get; set; }
        public double VPAmbientSalinity { get; set; }
        public double VPAmbientTemperature { get; set; }
        public double BackgroundConcentration { get; set; }
        public double PollutantDecayRate { get; set; }
        public double FarFieldCurrentSpeed { get; set; }
        public double FarFieldCurrentDirection { get; set; }
        public double FarFieldDiffusionCoefficient { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual VPScenario VPScenario { get; set; }
    }
}
