//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPSelectedResult
    {
        public int VPScenarioID { get; set; }
        public int ResType { get; set; }
        public double Concentration { get; set; }
        public double Dilution { get; set; }
        public double FarFieldWidth { get; set; }
        public double DispersionDistance { get; set; }
        public double CorrectedDistance { get; set; }
        public double TravelTime { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual VPScenario VPScenario { get; set; }
    }
}
