//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class WQMDefPrecipStation
    {
        public int DefPrecipStationID { get; set; }
        public int SubsecDefPrecipStationID { get; set; }
        public int PrecipStationID { get; set; }
        public int SelectionOrder { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual WQMPrecipStation WQMPrecipStation { get; set; }
        public virtual WQMSubsecDefPrecipStation WQMSubsecDefPrecipStation { get; set; }
    }
}
