//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class WQMPrecipStation
    {
        public WQMPrecipStation()
        {
            this.WQMDefPrecipStations = new HashSet<WQMDefPrecipStation>();
            this.WQMPrecipValues = new HashSet<WQMPrecipValue>();
            this.WQMRuns = new HashSet<WQMRun>();
        }
    
        public int PrecipStationID { get; set; }
        public string PrecipStnCode { get; set; }
        public string PrecipStnName { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public decimal LatDeg { get; set; }
        public decimal LongDeg { get; set; }
        public int Elevation { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<WQMDefPrecipStation> WQMDefPrecipStations { get; set; }
        public virtual ICollection<WQMPrecipValue> WQMPrecipValues { get; set; }
        public virtual ICollection<WQMRun> WQMRuns { get; set; }
    }
}
