//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempDataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class WQMTide
    {
        public WQMTide()
        {
            this.WQMRuns = new HashSet<WQMRun>();
            this.WQMRuns1 = new HashSet<WQMRun>();
        }
    
        public int TideID { get; set; }
        public string TideCode { get; set; }
        public string TideName { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<WQMRun> WQMRuns { get; set; }
        public virtual ICollection<WQMRun> WQMRuns1 { get; set; }
    }
}
